### ISSUE TITLE
Problem with same GameTask in a row

### ISSUE THREAD

**Issue by The-Huginn** [The-Huginn/party-game#3]
When the same GameTask is used two times in a row the following error can be examined. To circumvent it the following condition was added (to not allow repeating the same task twice in a row)

GameSession#nextTaskUni => `if (!gameTask.isResolvable(resolutionContext) || (currentTask != null && currentTask.gameTask.equals(gameTask)))`

However it would be still nice to remove this problem. It can be achieve by creating (or reusing TestGameService#testRepeatingTaskNotRemoved) with a single repeating task and invoking `game/task/next` at least twice.

```
Test TestGameService#testRepeatingTaskNotRemoved(UniAsserter) failed 
: java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <500>.

	at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
	at com.thehuginn.TestGameService.lambda$testRepeatingTaskNotRemoved$92(TestGameService.java:571)
	Suppressed: org.hibernate.exception.ConstraintViolationException: error executing SQL statement [ERROR: duplicate key value violates unique constraint "resolvedtask_gametask_id_key" (23505)] [insert into ResolvedTask (gameTask_id,id) values ($1,$2)]
```

**Comment by The-Huginn** [comment]
This is solved thanks to the fc5e1d6
